const $=id=>document.getElementById(id);
let authMode='login';
let current='home';
let historyStack=[];
const users=[
  {name:'Ayesha',id:'ST-1001',flag:'🇵🇰',avatar:'👩'},
  {name:'Sana',id:'ST-1002',flag:'🇸🇦',avatar:'🧕'},
  {name:'Zara',id:'ST-1003',flag:'🇦🇪',avatar:'👸'},
  {name:'Hina',id:'ST-1004',flag:'🇵🇰',avatar:'🌸'},
  {name:'Mahi',id:'ST-1005',flag:'🇮🇳',avatar:'😊'},
  {name:'Nida',id:'ST-1006',flag:'🇵🇰',avatar:'⭐'}
];
const coin='<img class="coin" src="assets/coin.svg" alt="coin">';
const coinBig='<img class="coin big" src="assets/coin.svg" alt="coin">';
window.onload=()=>setTimeout(()=>{showScreen('auth')},900);
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function setAuth(mode){authMode=mode;$('loginTab').classList.toggle('active',mode==='login');$('signupTab').classList.toggle('active',mode==='signup');$('signupFields').classList.toggle('hidden',mode!=='signup')}
function enterApp(){let email=($('emailInput')?.value||'').trim();let pass=($('passInput')?.value||'').trim();if(!email||!pass){toast('Enter demo email and password');return}if(authMode==='signup'){let age=Number(($('ageInput')?.value||0));if(age && age<18){toast('18+ required');return}}showScreen('app');go('home',false)}
function adminQuick(){showScreen('app');go('admin',false)}
function forgotDemo(){toast('Password reset screen ready')}
function logout(){toggleMenu(false);showScreen('auth')}
function toggleMenu(v){$('sidebar').classList.toggle('open',v);$('shade').classList.toggle('show',v)}
function navButtonClick(){ if(current==='home') toggleMenu(true); else back(); }
function setHeader(title,sub=''){ $('pageTitle').innerText='Star Chat'; $('pageSub').innerText=title; $('navBtn').innerText=current==='home'?'☰':'←'; }
function setBottom(page){document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
function go(page,push=true){toggleMenu(false);if(push && current!==page) historyStack.push(current);current=page;setBottom(['home','moments','rooms','messages','profile'].includes(page)?page:'');render(page);}
function back(){ if(historyStack.length){go(historyStack.pop(),false)} else go('home',false); }
function toast(t){const el=$('toast');el.innerText=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1400)}
function userCards(){return `<div class="grid">${users.map((u,i)=>`<div class="card"><div class="avatar online">${u.avatar}</div><h4>${u.name} ${u.flag}</h4><p>Online now</p><span class="user-id">ID ${u.id} ${u.flag}</span><br><span class="vip">VIP${i%3+1}</span><button class="action sayhi" onclick="openChat('${u.name}')">Chat 💬</button></div>`).join('')}</div>`}
function render(page){let html='',title='Discover',sub='Star Chat';
 if(page==='home'){title='Discover';html=`<div class="ad"><div><b>AD SPACE READY</b><span onclick="go('wallet')">Learn More</span></div></div><div class="chips"><button class="chip active" onclick="tabDemo(this,'Recommend')">⭐ Recommend</button><button class="chip" onclick="tabDemo(this,'New Users')">🟢 New Users</button><button class="chip" onclick="tabDemo(this,'Following')">👥 Following</button><button class="chip" onclick="go('search')">🔍 Search</button></div><div id="homeList">${userCards()}</div>`}
 else if(page==='search'){title='Search Users';html=`<div class="hero"><h2>Find Stars</h2><p>Search by name, ID, online status and VIP badge.</p></div><input placeholder="Search user name or ID" oninput="searchDemo(this.value)"><div class="chips"><button class="chip active">Online</button><button class="chip">New</button><button class="chip">VIP</button><button class="chip">Friends</button></div><div id="searchList">${userCards()}</div>`}
 else if(page==='profile'){title='My Profile';html=profileHTML()}
 else if(page==='wallet'){title='Wallet';html=walletHTML()}
 else if(page==='tasks'){title='Tasks';html=`<div class="hero"><h2>Daily Tasks</h2><p>Complete profile actions and earn coins.</p></div><div class="list"><div class="card list-card"><div class="avatar">✅</div><div class="grow"><h4>Daily Check-in</h4><p>Claim once daily</p></div><button class="action gold" onclick="coinRain();toast('Claimed')">Claim</button></div><div class="card list-card"><div class="avatar">📸</div><div class="grow"><h4>Upload 4 photos</h4><p>Beginner task</p></div><button class="action" onclick="go('profile')">Open</button></div><div class="card list-card"><div class="avatar">💬</div><div class="grow"><h4>Say Hi to 5 users</h4><p>Social task demo</p></div><button class="action green" onclick="go('home')">Start</button></div></div>`}
 else if(page==='vip'){title='VIP Center';html=`<div class="hero"><h2>👑 VIP Center</h2><p>VIP badge, special frame and premium label.</p></div><div class="grid"><div class="card"><h4>VIP 1</h4><p>Gold badge + frame</p><button class="action gold" onclick="toast('VIP demo')">View</button></div><div class="card"><h4>VIP 2</h4><p>More following + who viewed me</p><button class="action gold" onclick="toast('VIP demo')">View</button></div></div>`}
 else if(page==='gifts'){title='Gifts';html=giftHTML()}
 else if(page==='settings'){title='Settings';html=`<div class="list"><div class="card list-card"><div class="avatar">🔔</div><div class="grow"><h4>Notifications</h4><p>On</p></div><button class="action">Edit</button></div><div class="card list-card"><div class="avatar">🔒</div><div class="grow"><h4>Privacy</h4><p>Safe chat mode</p></div><button class="action">Edit</button></div></div>`}
 else if(page==='moments'){title='Moments';html=`<div class="hero"><h2>Moments</h2><p>Photo posts and social feed UI.</p></div><div class="list"><div class="card list-card"><div class="avatar online">👸</div><div class="grow"><h4>Zara posted a photo</h4><p>❤️ 24 likes • 2 gifts</p></div><button class="action" onclick="toast('Liked')">Like</button></div><div class="card list-card"><div class="avatar">🌸</div><div class="grow"><h4>Hina shared a moment</h4><p>Just now</p></div><button class="action green">Follow</button></div></div>`}
 else if(page==='rooms'){title='Rooms';html=`<div class="hero"><h2>Voice Rooms</h2><p>Future voice ready. Current UI demo.</p></div><div class="list"><div class="card list-card"><div class="avatar online">🎙</div><div class="grow"><h4>Global Star Room</h4><p>37 members online</p></div><button class="action" onclick="openRoom()">Join</button></div><div class="card list-card"><div class="avatar">👑</div><div class="grow"><h4>VIP Lounge</h4><p>VIP users only</p></div><button class="action gold">VIP</button></div></div>`}
 else if(page==='messages'){title='Messages';html=`<div class="chips"><button class="chip active">All</button><button class="chip">Online</button><button class="chip">Unread</button><button class="chip">Friends</button></div><div class="list">${users.slice(0,5).map((u,i)=>`<div class="card list-card" onclick="openChat('${u.name}')"><div class="avatar online">${u.avatar}</div><div class="grow"><h4>${u.name} ${u.flag}</h4><p>${i%2?'Where did you come from?':'Tap to open private chat'}</p><span class="user-id">ID ${u.id} ${u.flag}</span></div><span class="badge gold">${i+1}</span></div>`).join('')}</div>`}
 else if(page==='admin'){title='Admin Panel';html=adminHTML()}
 else if(page==='adminUsers'){title='Admin Users';html=`<input placeholder="Search user / email / ID"><div class="list"><div class="card list-card"><div class="avatar online">👤</div><div class="grow"><h4>Demo User</h4><p>ID ST-1001 • Active</p></div><button class="action" onclick="toast('User opened')">Open</button></div></div>`}
 else if(page==='adminCoins'){title='Admin Coins';html=`<div class="hero"><h2>${coin} Coin Management</h2><p>Search user and add/remove coins in Firebase later.</p></div><input placeholder="User email / name / ID"><div class="row"><input placeholder="Coin amount" type="number"><select><option>Add Coins</option><option>Remove Coins</option></select></div><button class="btn main" onclick="coinRain();toast('Coins updated demo')">Update Coins</button>`}
 else if(page==='adminRooms'){title='Admin Rooms';html=`<div class="list"><div class="card list-card"><div class="avatar">🎙</div><div class="grow"><h4>Global Room</h4><p>Visible</p></div><button class="action green" onclick="toast('Room ON')">ON</button></div><div class="card list-card"><div class="avatar">👑</div><div class="grow"><h4>VIP Room</h4><p>Hidden</p></div><button class="action gold" onclick="toast('Room OFF')">OFF</button></div></div>`}
 else if(page==='adminPopup'){title='Popup Ads';html=`<div class="hero"><h2>📢 Popup Offer</h2><p>Admin can add banner/popup offer later.</p></div><input placeholder="Popup title"><input placeholder="Offer text"><button class="btn main" onclick="toast('Popup saved')">Save Popup</button>`}
 $('content').innerHTML=html;setHeader(title,sub);}
function profileHTML(){return `<div class="profile-cover"><div class="profile-dp"><img src="assets/star-logo.png"></div><h2>Rana Tehseen</h2><p>ID ST-1001 🇵🇰 • Pakistan</p><span class="vip">👑 VIP 1</span> <span class="badge">Online</span></div><div class="profile-actions"><button class="action green" onclick="toast('Followed')">Follow</button><button class="action" onclick="openChat('Star User')">Message</button><button class="action gold" onclick="go('gifts')">Gift</button></div><div class="grid stats"><div class="card stat"><b>128</b><span>Following</span></div><div class="card stat"><b>1.2K</b><span>Followers</span></div><div class="card stat"><b>85</b><span>Friends</span></div><div class="card stat"><b>314</b><span>Visitors</span></div></div><div class="section-title"><h3>Profile Tools</h3></div><div class="shortcuts"><div class="short" onclick="go('wallet')">${coin}<div>Wallet<small>Buy coins</small></div></div><div class="short" onclick="go('vip')">👑<div>VIP<small>Badges</small></div></div><div class="short" onclick="go('tasks')">✅<div>Tasks<small>Daily bonus</small></div></div><div class="short" onclick="go('gifts')">🎁<div>Gifts<small>Gift store</small></div></div></div><div class="section-title"><h3>Photo Album</h3><button class="action" onclick="toast('Photo upload demo')">+ Add</button></div><div class="album">${Array.from({length:9},(_,i)=>`<div class="slot ${i>5?'locked':''}">${i===0?'⭐':i>5?'🔒':'+'}</div>`).join('')}</div>`}
function walletHTML(){return `<div class="hero wallet-hero">${coinBig}<div><h2>Wallet</h2><p>Coin balance is hidden on normal screens.</p></div></div><div class="grid"><div class="card"><h4>Daily Bonus</h4><p>Claim once daily</p><button class="action gold" onclick="coinRain();toast('Bonus claimed')">Claim</button></div><div class="card"><h4>Buy Coins</h4><p>WhatsApp top-up</p><button class="action green" onclick="openBuy()">Buy</button></div></div><div class="section-title"><h3>Coin History</h3></div><div class="list"><div class="card list-card"><div class="avatar">${coin}</div><div class="grow"><h4>Signup Bonus</h4><p>+50 coins</p></div><span class="badge gold">Done</span></div><div class="card list-card"><div class="avatar">💬</div><div class="grow"><h4>Paid Chat</h4><p>-10 coins</p></div><span class="badge">Demo</span></div></div>`}
function giftHTML(){return `<div class="hero"><h2>Gift Store</h2><p>Send gifts using coins.</p></div><div class="gift-row"><div class="gift"><div class="emoji">🌹</div><b>Rose</b><br><span class="price">${coin}10</span></div><div class="gift"><div class="emoji">💖</div><b>Heart</b><br><span class="price">${coin}50</span></div><div class="gift"><div class="emoji">👑</div><b>Crown</b><br><span class="price">${coin}100</span></div><div class="gift"><div class="emoji">🍬</div><b>Jalebi</b><br><span class="price">${coin}30</span></div><div class="gift"><div class="emoji">🇵🇰</div><b>Pakistan</b><br><span class="price">${coin}99</span></div><div class="gift"><div class="emoji">🎁</div><b>Box</b><br><span class="price">${coin}500</span></div></div>`}
function adminHTML(){return `<div class="hero"><h2>🛡 Admin Dashboard</h2><p>All admin buttons open proper sections.</p></div><div class="admin-menu"><button onclick="go('adminUsers')">👥 Users Management</button><button onclick="go('adminCoins')">${coin} Add / Remove Coins</button><button onclick="go('adminRooms')">🎙 Rooms ON/OFF</button><button onclick="go('adminPopup')">📢 Popup Ads</button><button onclick="go('gifts')">🎁 Gifts Management</button><button onclick="go('settings')">⚙️ App Settings</button></div>`}
function tabDemo(btn,name){document.querySelectorAll('.chips .chip').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$('homeList').innerHTML=name==='Following'?`<div class="empty"><div><div class="people">👥</div><h3>No following yet</h3><p>Follow users to see them here.</p></div></div>`:userCards();}
function searchDemo(v){$('searchList').innerHTML=v.trim()?userCards():`<div class="empty"><div><div class="people">🔍</div><h3>Start searching</h3><p>Type name or ID above.</p></div></div>`}
function openChat(name){go('messages');setTimeout(()=>{ $('content').innerHTML=`<div class="hero"><h2>${name}</h2><p>Private chat UI demo</p></div><div class="card"><p>Hello! Nice to meet you 😊</p></div><div class="card" style="margin-top:10px"><p>Type message below. Failed icon will show later when coins end.</p></div><div style="position:absolute;left:14px;right:14px;bottom:88px;display:flex;gap:8px"><input placeholder="Say something" style="margin:0"><button class="action" onclick="toast('Message sent demo')">Send</button></div>`;$('pageTitle').innerText='Star Chat';$('pageSub').innerText=name;$('navBtn').innerText='←';current='chat';},0)}
function openRoom(){go('rooms');setTimeout(()=>{$('content').innerHTML=`<div class="hero"><h2>Global Star Room</h2><p>Room UI demo • 37 users online</p></div><div class="grid">${users.map(u=>`<div class="card"><div class="avatar online">${u.avatar}</div><h4>${u.name} ${u.flag}</h4><span class="user-id">ID ${u.id}</span><br><span class="vip">Speaker</span></div>`).join('')}</div><div style="position:absolute;left:14px;right:14px;bottom:88px;display:flex;gap:8px"><input placeholder="Say something"><button class="action gold" onclick="go('gifts')">🎁</button></div>`;$('pageTitle').innerText='Star Chat';$('pageSub').innerText='Global Room';current='room';},0)}
function openBuy(){document.querySelector('.phone').insertAdjacentHTML('beforeend',`<div class="modal"><div class="modal-box"><button class="modal-close" onclick="this.closest('.modal').remove()">×</button>${coinBig}<h2>Buy Coins</h2><p>Fast top-up through Star Chat team.</p><button class="btn main" onclick="location.href='https://wa.me/923494264051?text=Hello%20Star%20Chat%20Team,%20I%20want%20to%20buy%20coins.'">Contact WhatsApp</button></div></div>`)}
function coinRain(){for(let i=0;i<24;i++){let img=document.createElement('img');img.src='assets/coin.svg';img.className='rain';img.style.left=Math.random()*100+'%';img.style.animationDelay=(Math.random()*0.55)+'s';document.querySelector('.phone').appendChild(img);setTimeout(()=>img.remove(),1900)}}
